### ISSUE TITLE
Mode NOTIFICATION does not work on version 4.4.2 of android

### ISSUE THREAD

**Issue by frozendragon498** [ACRA/acra#178]
When i use this option and press on notification nothing happens I change to dialog and that works fine. Here is the complete config.
@ReportsCrashes(
	      formKey = "", // This is required for backward compatibility but not used
	      formUri = [Censored],
	      mode = ReportingInteractionMode.NOTIFICATION,
	      httpMethod = org.acra.sender.HttpSender.Method.POST,
	      reportType = org.acra.sender.HttpSender.Type.JSON,
          resToastText = R.string.crash_toast_text, 
          resNotifTickerText = R.string.crash_notif_ticker_text,
          resNotifTitle = R.string.crash_notif_title,
          resNotifText = R.string.crash_notif_text,
          resNotifIcon = android.R.drawable.stat_notify_error, 
          resDialogText = R.string.crash_dialog_text,
          resDialogIcon = android.R.drawable.ic_dialog_info, 
          resDialogTitle = R.string.crash_dialog_title, 
          resDialogCommentPrompt = R.string.crash_dialog_comment_prompt,
          resDialogOkToast = R.string.crash_dialog_ok_toast
	  )
To be clear this work fine until i updated the device from version 4.2 to 4.4.

**Comment by cbdonohue** [comment]
Confirmed not working Nexus 5 4.4

**Comment by william-ferguson-au** [comment]
So, some one who uses notifications interested in digging and finding out what is going wrong and provide a fix?

**Comment by timrae** [comment]
As per the documentation:

> The DIALOG mode is introduced in ACRA 4.3 as an experimental feature, aiming at replacing the NOTIFICATION mode as it is more user friendly.

So just deprecate / remove it...? Dialog mode is working fine; no need for a temporary notification.

**Comment by william-ferguson-au** [comment]
Fixed in #227 

@timrae,  I think Dialog is a better way of alerthing the user than Notification. But I don't thik we should remove it. Even deprecating seems harsh. If they like it let them use it.

**Comment by timrae** [comment]
I can see how *just* a notification might be useful to a small minority, as
it's more persistent than a toast, but a notification that opens up a
dialog when tapped is a bit silly IMO... It only makes sense to me in the
correct historical context that it was a means to an end.

Retaining it just unnecessarily adds pressure on you for support and
maintenance, and makes the wiki more bloated than it needs to be. Not to
mention that it's apparently broken anyway...?!

If you really wanna keep it, I think it makes more sense as a separate
variable to customise the dialog mode rather than a whole new mode of
operation. E.g. Does it work with the new custom dialog?

**Comment by timrae** [comment]
Sorry I didn't see the Fixed part of the message
