### ISSUE TITLE
Unable to find setConfig API in acra 4.6.3 version

### ISSUE THREAD

**Issue by nvoora** [ACRA/acra#281]
Hi Team,

I am unable to find setConfig API in acra 4.6.3 version.Is it deprecated? How can i achieve this functionality?

Thanks,
Vamsi

**Comment by molexx** [comment]
The changelog says it's been removed.

I would like it to stay please!

I use it when my app is in dev/testing, I don't want dev/testing reports going to my production backend but instead go to the internal backend on the LAN. ACRA.init() is called from Application.onCreate() and my app won't have worked out that it's in the test environment by then. Code running later in the app's initialization - in a non-Main thread - calls getConfig(), changes the target URI and login details, then calls setConfig().

I appreciate all users may not have a use like this but I find it convenient.

**Comment by william-ferguson-au** [comment]
#setConfig was removed because there are config attributes that need to be
known at #init and setting them afterwards led people to believe that they
wer ehaving an effect when they weren't.

What you can do is to use use ACRA#init(Application, ACRAConfiguration) and
for your testing environment populate it as you need by having an
overloaded factory for it.
ᐧ

**Comment by nvoora** [comment]
When i use init config method it was not working fine.
In the Application class i use @ReportCrashes and in oncreate i am giving  ACRA.init(this);.
In the Activity class i am giving
ACRAConfiguration acraConfig = ACRA.getConfig();
acraConfig.setMailTo("xyz@gmail.com");
ACRA.init(getApplication(), acraConfig);
ACRA.getErrorReporter().handleException(null);

Then i am unable to get the mail window when i set dynamically using above code.But when i specify in @ReportCrashes i am able to get mail window.When i set dynamically i am getting the below warning in logcat:-
06-11 05:55:18.633: W/ACRA(3430): ACRA#init called more than once. Won't do anything more.

So how can i set the configuration dynamically.Correct me if i am doing any wrong.

**Comment by molexx** [comment]
Could there be way to denote which attributes can be changed after init() and which not?
Or is it possible to un-init and re-init() from scratch?

Determining my target backend before init() would have to be done in a new Thread and so other application code might try and log to ACRA before init() has been called.

This rules out the possibility of apps changing backend - and any other attributes that can currently be changed - dynamically whilst the app is open. Personally I use it to separate production from testing, it's possible that other ACRA users have different needs.
If it's driven by some user-changeable variable such as a SharedPreference it would require the app to be closed, process killed, and re-opened again because init() can't be called twice.

The Javadoc for ACRAConfiguration says: "This class is to be used if you need to apply dynamic settings. This is needed for example when using ACRA in an Android Library Project since ADT v14 where resource ids are not final anymore and can't be passed as annotation parameters values. "



@nvoora if you can determine the email address in your Application.onCreate() before calling init() for the first time you can do what @william-ferguson-au suggests and pass the configuration as the second parameter to init(). There's no need to do anything in Activity.onCreate().
Although I'm not sure whether ACRA.getConfig() will work (return an ACRAConfiguration built from the annotation) before init() has been called.

**Comment by william-ferguson-au** [comment]
@nvoora @molex ACRA was never designed to have its config modified after initialisation. setConfig() was provided to allow configuration when annotations could not be used.

@nvoora You can construct your own instance of ACRAConfiguration in your Application#onCreate and populate it with the mailTo attribute. You can then pass that to ACRA#init().

@molexx I need to understand your use case better. I don't understand why you would need another thread to determine your target backend. My understanding is that you want different backend targets for development and production. There are several ways you could do this. One would be to shadow your Application lcass (and use annotations) or shadow an Configuration factory or the config for a configuration factory.

**Comment by molexx** [comment]
I didn't realise setConfig() wasn't meant to be used like that, and others might be doing the same.

In my case init() is called with defaults then it checks the local network to see if the internal ACRA backend server is available and if so it calls setConfig() to switch to use that. The local network checking can't be done on the main thread as it'll slow app launch. There is a time window where reports could go to the wrong place but I'd rather that than miss some reports.
Internal testing - both manual and automated - is done using the same build that is released. If I were to class shadow I'd still need to check the network first in order to decide which one to use at runtime which would delay the call to init().
I appreciate this is an uncommon use-case but I can't see a neat workaround.

Would setConfig() be OK if there were a way to restrict the attributes to just those that can be changed?

**Comment by william-ferguson-au** [comment]
@molexx that was exactly the reason for changing the API to reflect
intended use.

For what it's worth the way that most people seem to handle separation of
dev vs production errors is to filter them out at the server. The less
moving parts you have in your app, the less likely it is to break, and
that's especially a concern with the system you are using to report errors.

I'd rather not encourage change to the config after initialsation for
precisely the reason outlined above.
ᐧ

**Comment by nvoora** [comment]
Thanks @william-ferguson-au , I understood how to set configuration
