### ISSUE TITLE
Min SDK Froyo ?

### ISSUE THREAD

**Issue by xmenxwk** [ACRA/acra#350]
I just saw the source of Acra, and realize it that from 4.7 it only supports Froyo. But what about pre-froyo versions. No wonder I no longer receive error reports from API 4. Is there any solution to that ?

**Comment by william-ferguson-au** [comment]
As of 4th Jan 2016 only 0.2% of devices have Froyo on them.
http://developer.android.com/about/dashboards/index.html

There are bugger all devices running anything less than Froyo. Yes, some exist but they are collectors items. Do you really want to spend your precious development resource twisting your app such that it can support a dwindling number of museum pieces?

You no longer receive error reports from API 4 (aka Donut or Android 1.6) because it was released in Sept 2009. And people have long since upgraded their phones or had the OS upgraded on them.

**Comment by xmenxwk** [comment]
Please do not get me wrong. People usually misunderstand me.
It doesn't matter how many devices are using what android version. My older app which currently support all devices from API 4 to newest. Because since its first version, API 4 was chosen to be the base android version. And I intend to keep it that way. As once I can support API 4 and I can keep maintain it. Its not that hard. I wouldn't spend hours for it. Its really not that hard.The more new android version you've the more features will get enabled. Its all just simple if...else blocks.

As a friendly advice, libraries must maintain to their base version as well. Like ACRA. I know its free and you've done very excellent job. I'm very grateful. I cannot thank you enough. But changing the base version like that is not a good idea. If you once supported API4 you can keep support it. It makes me feel very unconformable because if it happens once it will happen again, maybe next base version will be API11 or something. Not good. No offense please. If Froyo is supported, its not hard to support Donut 1.6.

I did receive few reports from API 4 which helped me find the bug and resolved it. Again, ACRA is best bug reporting library, please keep it that way.

**Comment by william-ferguson-au** [comment]
It's not simple. It adds to complexity. 10% of development cost is initial, 90% is in maintenance. 
If you want to survive you need to keep your maintenance costs low.

Newer versions of Android have dropped support for some APIs. This means that we either need to switch to the replacement APIs or introduce a dependency on 3rd party libraries.

Think of it in ROI terms. The earlier versions of Android will continue to dwindle over time reducing  their value to you. The newer versions of Android will increase over time providing more value to your app. But you want to anchor your cost base to supporting the dwindling resource.

It doesn't make good business sense.

Of course you are free to fork ACRA and maintain it as best you can to support whatever versions to believe is necessary. But ACRA users wanted support for the new Android versions, so that's where we went.

**Comment by xmenxwk** [comment]
Complexity ? Everything is complex these days. We cant run away from complexity. Even the current ACRA version is complex.

No, it doesn't make sense. There is no extra maintenance cost, there is no crash if new Android version has removed older APIs. Yes Android devs removed old apache http library and asked to use HttpURLConnection instead or shove big lib jar to apk. But where is the problem ? HttpURLConnection exists since API 1.

I'm not saying to code for older version, but if you once coded for it you can keep it there. For example, now you support Froyo, in next few years it will be very old, but you can keep support it. Its just to introduce new classes. 

The bad thing to do would be coding specially for API4, but not keeping what already been coded.

My apps are maintained like this, yes if I start developing a new app. I would use a higher version as base version. And I'm not strictly sticked to API4 for older apps. But since I can support I do, and if they start to take more time of me I would move to newer API without a second thought.

Yes I can fork ACRA, but I wouldn't spend my time to fix a library just for API 4. As I said earlier, you had support for API 4 but now you lost it.

I like ACRA but please try to not change its min sdk in future. That would be very kind of you. :) Again I cant thank you enough for saving a lot of my time by making this library publicly available.
