### ISSUE TITLE
Auto create github issue (feature request)

### ISSUE THREAD

**Issue by bancer** [ACRA/acra#353]
A nice feature would be to autocreate a github issue on any reported crash. As a developer I would specify the repository and credentials and the issue would be posted by using [github API](https://developer.github.com/v3/issues/#create-an-issue).

**Comment by william-ferguson-au** [comment]
You could do this by creating your own ReportSender and configuring it within ACRA
See https://github.com/ACRA/acra/wiki/Report-Destinations#implementing-your-own-sender

But I would **STRONGLY** recommend against it, as you will generate endless numbers of issues due to strange device/framework errors that are nothing to do with your app. Along with potentially millions of instances of a single error generating millions of github issues. Github would not be happy.

The appropriate solution for this is to aggregate your crash on a crash report server and have the report server be able to automatically open and link to an issue on your bug tracking application.
