### ISSUE TITLE
Minimum supported version

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#367]
What is the minimum supported version? Readme states 8, but build.gradle uses 4.

**Comment by william-ferguson-au** [comment]
8 as is described in the docs and the AndroidManifest.

I don't maintain the Gradle build file as it is  not used to build ACRA.
That file was added but someone who wanted to use Frame as the build tool.

**Comment by F43nd1r** [comment]
then why do you access Build.VERSION.SDK_INT with reflection?

**Comment by william-ferguson-au** [comment]
Because we needed to once upon an age ago, and that relic hasn't been found
and removed. Is it a problem?

**Comment by F43nd1r** [comment]
other than performance, no. I'm cleaning that up though. Do you mind if I add support annotations as dependency to the project? I'm checking through the code, and it would help especially for the classes which can be extended e.g. to show users that they should call super.

**Comment by william-ferguson-au** [comment]
Define: support annotations

If prefer to not add any dependencies.

**Comment by F43nd1r** [comment]
http://tools.android.com/tech-docs/support-annotations this is a pure compile-time addition. It does not change the resulting files, it only adds checks to the build (I think they are Lint checks). It helps to prevent nullpointers, invalid states of extending classes or callers, etc.

**Comment by william-ferguson-au** [comment]
How are you planning on having them generate into the ACRA AAR?
It appears that it only happens when using Gradle to build a library.

**Comment by F43nd1r** [comment]
annotations are shipped in class files as normal (similar to e.g. @Deprecated), only those which need additional data (like @IntDef) are shipped in an extra zip. So this should work also without gradle.

Additionally, I recommend you to try out Android studio with gradle. It's great, and it's the supported way of writing and distributing android code.

**Comment by william-ferguson-au** [comment]
Are you sure that's its only the @IntDef annotation that is included in annotations.zip.
 My reading of "Using Annotations in your Own Libraries" is that there was probably descriptors for all of them.

I've tried Android Studio. It's fine except that it pushes Gradle down your throat. I'm sure Gradle will be good in 2-3 years time. It might even make it to when Maven2 got to in 2006. 

Annotations in your source are good if they can be used. Otherwise they just add to maintenance burden.

**Comment by F43nd1r** [comment]
Here is one of my libraries which uses both types of annotations. I was able to find e.g. @RawRes annotations in decompiled classfiles. Also in the annotation.zip there are only @IntDef annotations.

**Comment by william-ferguson-au** [comment]
ACRA is built using JDK6 - See https://github.com/ACRA/acra/blob/master/pom.xml#L134

ACRA predates Android's move to JDK6. So it is not surprising that there are statement that can be simplified. Though having said that I haven't noticed any.

Strongly suggest you split any PR up so that changes are grouped into a discrete functional change per PR. That will make it much easier for me to be able to verify changes.

**Comment by F43nd1r** [comment]
Anyways, this has nothing to do with the original issue.
