### ISSUE TITLE
ACRA process conflict with main process?

### ISSUE THREAD

**Issue by EMIN3M1986** [ACRA/acra#410]
Hi.
A few days ago I open an issue that explain about conflicting the acra process with main app process.
I updated the Acra to latest version but nothing changed. 
Let me explain. For example I start a service normally, like this:
 
                    Intent intent = new Intent(SmsApp.getInstance(), ConsumerService.class);
                    SmsApp.getInstance().startService(intent);

Sometime service run on main process and sometime run on ACRA process or some threads that has same problem. 

I configure ACRA exactly as you said.
As you see in bellow some my Logs show in Acra Process like this:
 
                   03-26 10:10:16.855 12311-12346/com.gapafzar.gap:acra D/gap1: RabbitmqService msg

It has to be like this:

                   03-26 10:10:16.974 12297-12354/com.gapafzar.gap:gap D/gap1: RabbitmqService msg

what is the problem ?

**Comment by william-ferguson-au** [comment]
What is `SmsApp.getInstance()`?

From where do you call?
`
Intent intent = new Intent(SmsApp.getInstance(), ConsumerService.class);
SmsApp.getInstance().startService(intent);
`

If you are calling the above from `Application.onCreate` (for instance), then you will get 2 `ConsumeService` services started. One by your `gap` process and one by the `:acra` process, because starting the ACRA SenderService in another process starts a new version of your app in another process.

**Comment by EMIN3M1986** [comment]
I register ACRA in attachBaseContext() not in oncrate().

In my code getInstance() return the application class.

**Comment by william-ferguson-au** [comment]
Yes, but where do you make this call:
```
Intent intent = new Intent(SmsApp.getInstance(), ConsumerService.class);
SmsApp.getInstance().startService(intent);
```

**Comment by EMIN3M1986** [comment]
in application onCreate()

**Comment by william-ferguson-au** [comment]
Right, so as I was saying above.
_If you are calling the above from Application.onCreate (for instance), then you will get 2 ConsumeService services started. One by your gap process and one by the :acra process_

This is because on startup ACRA will (by default) start the SenderService in order to end any unsent reports. This causes your app to start again under the `:acra` processs.

You can void this by starting ACRA using `ACRA.init(yourApp, yourACRAconfig, false)`.

A better solution would be to check to see what process your are running under in `Application.onCreate` and don't start your service if it is the `:acra` process.

**Comment by EMIN3M1986** [comment]
thanks a lot. I try it :+1:

**Comment by EMIN3M1986** [comment]
Now I check the process name in onCreate() method and if the name equals with my process name let him go on. 
I know it's not the best way but actually it works. I will fix it later. 
Thanks a lot for you Guidance.

**Comment by william-ferguson-au** [comment]
That is the only way to test.

I have added a new method `ACRA.isACRASenderServiceProcess()` for ACRA-4.8.6 which will tell you the same thing.
