### ISSUE TITLE
CrashReportPersister

### ISSUE THREAD

**Issue by lytasky** [ACRA/acra#461]
why  edcdic is used not ascii   in CrashReportPersister.java

**Comment by william-ferguson-au** [comment]
What makes you think edcdic is used?
Can you give me a line number reference?

**Comment by lytasky** [comment]
if (!isEbcdic) {
                return load(new InputStreamReader(bis, "ISO8859-1")); //$NON-NLS-1$
            } else {
                return load(new InputStreamReader(bis)); //$NON-NLS-1$
            }
here  ？

**Comment by F43nd1r** [comment]
Not exactly the question, just related: it seems odd to require that much custom code to fulfill such a common job - persisting to and reading from a file. Is there a reason why this doesn't use one of the more obvious solutions, like JSON?

**Comment by william-ferguson-au** [comment]
I'm sorry @lytasky I can't find that reference anywhere in CrashReportPersister.
What line?

@F43nd1r Why? Because that's what was created by the original author of ACRA back in the dawn of time. Since it is entirely internal it could use any format and any mechanism. I suspect that it may have originally been hand rolled so as to avoid adding dependencies to the library.

**Comment by lytasky** [comment]
oh ,sorry  I forget to tell the  tag : acra-4.5.0

**Comment by william-ferguson-au** [comment]
Sorry @lytasky - no idea why ebcdic was used back then. Is isn't used now.

**Comment by william-ferguson-au** [comment]
NB ACRA-4.5.0 is more than 3 years old.

**Comment by lytasky** [comment]
ok.  got it.
