### ISSUE TITLE
CrashReportData toJSON gets wrong result when a key like x.x.xxxx in the sharedpreference

### ISSUE THREAD

**Issue by su1216** [ACRA/acra#492]
In my app, 1.6.2_end__protection and 1.6.2_begin_protection are the keys in my sharedpreference. 
Part of json of the CrashReportData.toJSON  is 
```
"1":{"6":{"2_end__protection":1470805461847,"2_begin_protection":1470805461637}}
```

I expected the result is 
```
{"1.6.2_end__protection":1470805461847, "1.6.2_begin_protection":1470805461637}
```

please forgive me my poor English...
acra version:4.9.0

**Comment by F43nd1r** [comment]
Relevant code is https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/util/JSONReportBuilder.java#L151. The problem is splitting is done on the full report, not only the sharedpreferences. If it is possible to change this control character at all, it would require a change in each and every collector. 

The only easy solution I can think of is to replace all points in sharedpreferences while collecting.
A more complex solution would be to somehow carry over a value how deep the JSONSUbTree mechanism should go...
Any thoughts/ideas/preferrences @william-ferguson-au ?

**Comment by william-ferguson-au** [comment]
I haven't thought it through in detail, but the clean solution looks like storing all the data from the collectors in Json objects right from the start. But that's a lot of change.

The workaround is to not use '.' as a delimiter in your shared prefs key name space.

**Comment by su1216** [comment]
These keys in my app are used by a third party jar. Now I use excludeMatchingSharedPreferencesKeys to exclude these keys with regex. Thanks
