### ISSUE TITLE
Instant run

### ISSUE THREAD

**Issue by dima74** [ACRA/acra#518]
Hello! Thank you for ACRA! I have a small question, could you answer it, please:
Is it true that I can't use both Acra and Instant run?
If so is it true that there is a conceptual problem, so it is impossible to achieve this even in future?
When I perform code changes I get this:
`Instant Run applied code changes and restarted the app. The app was restarted since it uses multiple processes.`
I don't post any code, because I get this message even in Hello World project (with adding acra as dependency and without adding strings like `Acra.init(this)`)

**Comment by william-ferguson-au** [comment]
I don't know the answer to that.

ACRA uses a separate process to ensure that crash reports are successfully pushed to the report server.

The Instant Run  user guide only makes this menton about multi process apps:

> Pushing changes to multi-process apps
> Instant Run only instruments your app's main process in order to perform hot swaps and warm swaps. When pushing code changes to other app processes, such as changes to a method implementation or an existing resource, Instant Run performs a cold swap
>

**Comment by F43nd1r** [comment]
This will not be fixed on ACRAs side. I expect that Instant run will support multiple processes in the future, as this was only introduced temporarily in beta6 of android studio.

>     Apps that were using multiple processes (via android:process in the manifest) were not being updated properly with Instant Run. For the time being, we have turned off Instant Run in such a scenario.

**Comment by arch-install** [comment]
Ok, thank you for answers.

**Comment by dima74** [comment]
OK, thank you for answers.

**Comment by robindijkhof** [comment]
I found some way to use ACRA with instant run:

Use `releaseCompile`instead of `compile` for ACRA in your gradle build: `releaseCompile 'ch.acra:acra:X.X.X'`

You probably have some file called `MyApplication` where you initialize ACRA. This is the same class you use in your manifest under you application tag. This file is in app/src/main/some/path/to/MyApplication.java

1. Copy this file and paste in app/src/debug/some/path/to/MyApplication.java and app/src/release/some/path/to/MyApplication.java
2. Delete app/src/main/some/path/to/MyApplication.java
3. In app/src/debug/some/path/to/MyApplication.java remove anything that has to do something with ACRA

Now you can use ACRA in you release builds and use instant run during debug.

**Comment by dima74** [comment]
@robindijkhof, thank you. I don't code for android anymore, but anyway it is very good that you find solution.
