### ISSUE TITLE
Reports are sent for ever

### ISSUE THREAD

**Issue by xi67** [ACRA/acra#595]
In 4.8.5, an app crash very often and my couchdb was down so the report try to be sent for ever (big amount of data).

Is it possible to limit the number of retry of reports and the number of reports in memory ?

**Comment by F43nd1r** [comment]
ACRA will only send 5 reports at once. Currently, reports saved to disk cannot be limited. ACRA should only retry sending a failed report after your application is restarted.

**Comment by xi67** [comment]
The problem is : if acralyzer have a problem or if report can't be integrated because of missing field or everything else, the report will be resent forever.

If a bug occur often the number of report will increase very quickly.
On a fleet of 20 phone with a bug which occur 2-3 times an hour when the acra server return after 10 days we have thousands of report et 40 Go of Data used (all fields activated).

This is a major issue.
If the server can't integrate the report, it should not be resend for ever.

**Comment by F43nd1r** [comment]
which http response code is sent by your server if the report cannot be integrated?

**Comment by xi67** [comment]
couchdb was stopped so no http response.
acra was unable to connect

**Comment by tslocum** [comment]
Hello, I've received a report of my app suddenly jumping from a few megabytes of data usage to over a gigabyte, due to constant attempts to send crash reports while my app fails to start a service.

I understand it may be difficult to add a limiting mechanism while the app is just starting to initialize, but perhaps a text file could be created containing a list of timestamps which reports were sent and their corresponding app (package).  Old entries could be pruned when checking to keep it slim.  This way, if the app recently crashed, we can immediately discard the report and help save users' data/battery.

**Comment by F43nd1r** [comment]
For ACRA 5.0.0, there is now a ReportLimiter module available. Example usage:

build.gradle:

```groovy
dependencies {
    compile 'com.faendir.acra:acra-http:5.0.0-alpha14'
    compile 'com.faendir.acra:acra-dialog:5.0.0-alpha14'
    //1. add limiter to application
    compile 'com.faendir.acra:acra-limiter:5.0.0-alpha14'
}
```

MyApplication.java:

```java
@AcraCore(reportFormat = StringFormat.JSON)
//2. configure limiter
@AcraLimiter(resIgnoredCrashToast = R.string.toast_text_no_send)
@AcraHttpSender(
        httpMethod = HttpSender.Method.POST,
        uri = "***")
@AcraDialog(
        resText = R.string.crash_dialog_text,
        resTheme = R.style.Theme_AppCompat_Light_Dialog)
```

**Comment by F43nd1r** [comment]
Closing this with the release of ACRA 5
