### ISSUE TITLE
Acra is required wake lock permisson?

### ISSUE THREAD

**Issue by AlexMercier** [ACRA/acra#647]
When I use http sender to send reports, without wake_lock permission i got a error.
Is it required to use this permission? 
acra version 5.1.0,  Android 5.1.1
```
:acra E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.package.myapp:acra, PID: 9808
java.lang.RuntimeException: Unable to start service org.acra.sender.SenderService@19ea9eb2 with 
Intent { cmp=com.package.myapp/org.acra.sender.SenderService (has extras) }:
java.lang.SecurityException: Neither user 10053 nor current process has android.permission.WAKE_LOCK
```

**Comment by F43nd1r** [comment]
Yes, it is required (and [included in 5.1.1](https://github.com/ACRA/acra/blob/master/acra-core/src/main/AndroidManifest.xml#L19)), because of [JobIntentService](https://developer.android.com/reference/android/support/v4/app/JobIntentService.html), which is required to support both pre-oreo and oreo devices.
