### ISSUE TITLE
Explain somewhere that WAKE_LOCK permission has maxSdkVersion attribute

### ISSUE THREAD

**Issue by sarbyn** [ACRA/acra#651]
In my project I use the WAKE_LOCK permission and when I've upgrating ACRA to the latest version the application has stop working.
After some research I found the 
`<uses-permission
        android:name="android.permission.WAKE_LOCK"
        android:maxSdkVersion="25" />`
in acra-core AndroidManifest.xml and then I've changed my project manifest with:
`<uses-permission android:name="android.permission.WAKE_LOCK"
        tools:node="replace"/>`

I think that it's better to declare somewhere in the install guide that acra-core add the maxSdkVersion, in order to warn the developer that something weird can happen with his application

**Comment by F43nd1r** [comment]
Now part of the new [Troubeshooting guide](https://github.com/ACRA/acra/wiki/Troubleshooting-Guide)

**Comment by mikehardy** [comment]
I see this in the troubleshooting guide now but this did trip me up, along with the ':acra'  android:process need for the crash process item. So I'm not disputing that they are documented, but I think they are important enough (especially that WAKE_LOCK one!) that there should be an AndroidManifest.xml section in Basic Setup now, as otherwise the need to modify the manifest isn't even mentioned but it can result in crash bugs so easily

**Comment by F43nd1r** [comment]
As of 5.2.0 this is a non-issue, see #690

**Comment by mikehardy** [comment]
Thus must have just caught me prior to 5.2.0 when we were on 5.1, thanks. Might still be worth it to mention the process name but that isn't likely a crash bug... Thanks!
