### ISSUE TITLE
ACRA Privacy Policy

### ISSUE THREAD

**Issue by KerstinMaur** [ACRA/acra#749]
Does ACRA have a privacy policy? What do I have to write in my privacy policy if I use ACRA?

_P.S. The question came up in this issue: nisrulz/app-privacy-policy-generator#45_

**Comment by F43nd1r** [comment]
Depending on configuration ACRA might send anything between no data and everything collectible to any server you want.
As a result, it is not possible to write a generic privacy policy for ACRA.

**Comment by nisrulz** [comment]
@F43nd1r is there any data ACRA collects by default (with out of the box setup)? 

Privacy Policy usually covers only that. Anything a user adds on their own to be collected via the service is on the user to disclose. In case the configuration is changed to send no data at all, the Privacy Policy doesn't get void, instead should mention the scenario.

Ofcourse this is something I have observed and I am no lawyer.

**Comment by F43nd1r** [comment]
>  is there any data ACRA collects by default (with out of the box setup)?

The default and recommended use of ACRA is to collect and send anonymized statistics of crashes within your app to you.

> Anything a user adds on their own to be collected via the service is on the user to disclose.

First I want important to note, that ACRA is **not** a service.
Second, when I talk of an ACRA user, I'm talking about a developer. The end user of an app using  ACRA has very limited options (or none, depending on configuration by the developer) to control ACRA.

> In case the configuration is changed to send no data at all, the Privacy Policy doesn't get void, instead should mention the scenario.

If ACRA is never sending any data, it is useless. 

> Ofcourse this is something I have observed and I am no lawyer.

I'm not a lawyer either, which is why I will avoid writing any official privacy policy for ACRA.

Someone with the respective knowledge should be able to write a tool which pieces together a privacy policy based on ACRA configuration. In this case I would gladly assist with my knowledge of the software.

**Comment by KerstinMaur** [comment]
Thanks for the clarification, @F43nd1r. 👍
